language: swift

xcode_project: eigami.xcodeproj 
xcode_scheme: eigami

cache:
  directories:
  - Carthage
  
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
