language: swift
xcode_project: eigami.xcodeproj # path to your xcodeproj folder
xcode_scheme: eigami
before_install:
    - brew update
    - brew upgrade carthage
install: carthage bootstrap --no-use-binaries --configuration Release --platform iOS