language: swift

xcode_project: eigami.xcodeproj 
xcode_scheme: eigami

osx_image: xcode9.2

cache:
  directories:
  - Carthage
  
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

script: 
  - xctool -project eigami.xcodeproj -scheme eigamiTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  
after_success:
  - bash <(curl -s https://codecov.io/bash)