language: swift
xcode_project: eigami.xcodeproj # path to your xcodeproj folder
xcode_scheme: eigami
before_install:
    - brew update
    - brew upgrade carthage
    - carthage bootstrap --no-use-binaries --platform ios